services:
  bank-app:
    build: .
    ports:
      - "3005:3005"
    depends_on:
      postgres:
        condition: service_healthy
      postgres_test:
        condition: service_started
      redis:
        condition: service_started
    command: sh -c "pnpm prisma migrate deploy && pnpm run start:dev"
    env_file:
      - ./.env

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: bankdb_nest
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: bankdb_nest_test
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  postgres_test_data:

